stages:
  - keycloak-dev
  - keycloak-new-dev
  - keycloak-preprod
  - keycloak-prod

keycloak-dev:
  stage: keycloak-dev
  tags:
    - sme-dev
  image: 
    name: alpine/k8s:1.22.9
    entrypoint: [""]
  before_script:
    - mkdir -p ~/.kube/
    - echo ${KUB_DEV} | base64 -d > ~/.kube/config
    - chmod o-r ~/.kube/config
    - chmod g-r ~/.kube/config
  script:
    - helm repo add codecentric https://codecentric.github.io/helm-charts
    - helm upgrade --create-namespace --install keycloak helm -n keycloak-dev -f helm/dev.yml
  only:
    - main
  when: manual

keycloak-new-dev:
  stage: keycloak-new-dev
  tags:
    - sme-new-dev
  image: 
    name: alpine/k8s:1.22.9
    entrypoint: [""]
  script:
    - helm repo add codecentric https://codecentric.github.io/helm-charts
    - helm upgrade --create-namespace --install keycloak helm -n keycloak-dev -f helm/dev.yml
  only:
    - main
  when: manual

keycloak-preprod:
  stage: keycloak-preprod
  tags:
    - sme-preprod
  image: 
    name: alpine/k8s:1.22.9
    entrypoint: [""]
  script:
    - helm repo add codecentric https://codecentric.github.io/helm-charts
    - helm upgrade --create-namespace --install keycloak helm -n keycloak-preprod -f helm/preprod.yml
  only:
    - main
  when: manual  

keycloak-prod:
  stage: keycloak-prod
  tags:
    - sme-prod
  image: 
    name: alpine/k8s:1.22.9
    entrypoint: [""]
  script:
    - helm repo add codecentric https://codecentric.github.io/helm-charts
    - helm upgrade --create-namespace --install keycloak helm -n keycloak-prod -f helm/prod.yml
  only:
    - main
  when: manual
